# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 200))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#0000d4\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/medicine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/supplier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/grocery-store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/exploratory-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 570, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #ff3333;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: none;\n"
"\n"
"    /* Glow merah */\n"
"    box-shadow: 0 0 10px rgba(255, 50, 50, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e62828;\n"
"    box-shadow: 0 0 14px rgba(255, 50, 50, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c71f1f;\n"
"    box-shadow: none;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 500))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#ffffff\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:#dddddd}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(20, 16, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("JFrame{\n"
"background-color:rgb(232, 232, 232)\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 231, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 70, 141, 121))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e1e1e1;\n"
"    border-radius: 18px;\n"
"    transition: 150ms;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #cfcfcf;\n"
"    box-shadow: 0px 2px 8px rgba(0,0,0,60);   /* efek keren */\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(20, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("\n"
"color: rgb(255, 255, 0);")
        self.label_16.setObjectName("label_16")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(170, 70, 141, 121))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e1e1e1;\n"
"    border-radius: 18px;\n"
"    transition: 150ms;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #cfcfcf;\n"
"    box-shadow: 0px 2px 8px rgba(0,0,0,60);   /* efek keren */\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(20, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(320, 70, 141, 121))
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e1e1e1;\n"
"    border-radius: 18px;\n"
"    transition: 150ms;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #cfcfcf;\n"
"    box-shadow: 0px 2px 8px rgba(0,0,0,60);   /* efek keren */\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_18.setObjectName("label_18")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(470, 70, 141, 121))
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e1e1e1;\n"
"    border-radius: 18px;\n"
"    transition: 150ms;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #cfcfcf;\n"
"    box-shadow: 0px 2px 8px rgba(0,0,0,60);   /* efek keren */\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(0, 20, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        self.label_19.setGeometry(QtCore.QRect(10, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        self.label_20.setGeometry(QtCore.QRect(50, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(20, 200, 291, 211))
        self.frame_9.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px; /* Sudut membulat */\n"
"    border: 1px solid #E0E0E0; /* Batas abu-abu tipis */\n"
"    padding: 15px; /* Jarak dari konten ke batas */\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 161, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.widget = QtWidgets.QWidget(self.frame_9)
        self.widget.setGeometry(QtCore.QRect(10, 40, 271, 51))
        self.widget.setObjectName("widget")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(10, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(130, 0, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.widget_2 = QtWidgets.QWidget(self.frame_9)
        self.widget_2.setGeometry(QtCore.QRect(10, 90, 271, 51))
        self.widget_2.setObjectName("widget_2")
        self.label_23 = QtWidgets.QLabel(self.widget_2)
        self.label_23.setGeometry(QtCore.QRect(10, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_2)
        self.label_24.setGeometry(QtCore.QRect(120, 0, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.widget_3 = QtWidgets.QWidget(self.frame_9)
        self.widget_3.setGeometry(QtCore.QRect(10, 140, 271, 51))
        self.widget_3.setObjectName("widget_3")
        self.label_25 = QtWidgets.QLabel(self.widget_3)
        self.label_25.setGeometry(QtCore.QRect(10, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_3)
        self.label_26.setGeometry(QtCore.QRect(120, 0, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setGeometry(QtCore.QRect(319, 200, 291, 211))
        self.frame_10.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px; /* Sudut membulat */\n"
"    border: 1px solid #E0E0E0; /* Batas abu-abu tipis */\n"
"    padding: 15px; /* Jarak dari konten ke batas */\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.widget_4 = QtWidgets.QWidget(self.frame_10)
        self.widget_4.setGeometry(QtCore.QRect(10, 40, 271, 51))
        self.widget_4.setObjectName("widget_4")
        self.progressBar = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar.setGeometry(QtCore.QRect(10, 20, 251, 16))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #F2F2F2;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #E74C3C,\n"
"        stop:1 #F1C40F\n"
"    );\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 40)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(-10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(170, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.widget_5 = QtWidgets.QWidget(self.frame_10)
        self.widget_5.setGeometry(QtCore.QRect(10, 90, 271, 51))
        self.widget_5.setObjectName("widget_5")
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 20, 251, 16))
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
"    background-color: #F2F2F2;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #E74C3C,\n"
"        stop:1 #F1C40F\n"
"    );\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.progressBar_2.setProperty("value", 60)
        self.progressBar_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setGeometry(QtCore.QRect(-10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setGeometry(QtCore.QRect(170, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.widget_6 = QtWidgets.QWidget(self.frame_10)
        self.widget_6.setGeometry(QtCore.QRect(10, 140, 271, 51))
        self.widget_6.setObjectName("widget_6")
        self.progressBar_3 = QtWidgets.QProgressBar(self.widget_6)
        self.progressBar_3.setGeometry(QtCore.QRect(10, 20, 251, 16))
        self.progressBar_3.setStyleSheet("QProgressBar {\n"
"    background-color: #F2F2F2;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #E74C3C,\n"
"        stop:1 #F1C40F\n"
"    );\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.progressBar_3.setProperty("value", 25)
        self.progressBar_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        self.label_12.setGeometry(QtCore.QRect(-10, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.widget_6)
        self.label_15.setGeometry(QtCore.QRect(170, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(20, 430, 591, 211))
        self.frame_11.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px; /* Sudut membulat */\n"
"    border: 1px solid #E0E0E0; /* Batas abu-abu tipis */\n"
"    padding: 15px; /* Jarak dari konten ke batas */\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setGeometry(QtCore.QRect(0, 10, 161, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.widget_7 = QtWidgets.QWidget(self.frame_11)
        self.widget_7.setGeometry(QtCore.QRect(10, 40, 571, 51))
        self.widget_7.setObjectName("widget_7")
        self.label_28 = QtWidgets.QLabel(self.widget_7)
        self.label_28.setGeometry(QtCore.QRect(10, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.widget_7)
        self.label_29.setGeometry(QtCore.QRect(320, 0, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_34 = QtWidgets.QLabel(self.widget_7)
        self.label_34.setGeometry(QtCore.QRect(160, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.widget_8 = QtWidgets.QWidget(self.frame_11)
        self.widget_8.setGeometry(QtCore.QRect(10, 90, 571, 51))
        self.widget_8.setObjectName("widget_8")
        self.label_30 = QtWidgets.QLabel(self.widget_8)
        self.label_30.setGeometry(QtCore.QRect(10, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.widget_8)
        self.label_31.setGeometry(QtCore.QRect(320, 0, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_35 = QtWidgets.QLabel(self.widget_8)
        self.label_35.setGeometry(QtCore.QRect(160, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.widget_9 = QtWidgets.QWidget(self.frame_11)
        self.widget_9.setGeometry(QtCore.QRect(10, 140, 571, 51))
        self.widget_9.setObjectName("widget_9")
        self.label_32 = QtWidgets.QLabel(self.widget_9)
        self.label_32.setGeometry(QtCore.QRect(10, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.widget_9)
        self.label_33.setGeometry(QtCore.QRect(320, 0, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.widget_9)
        self.label_36.setGeometry(QtCore.QRect(160, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_8.setText(_translate("MainWindow", "Stok Obat"))
        self.pushButton_2.setText(_translate("MainWindow", "Supplier"))
        self.pushButton_3.setText(_translate("MainWindow", "Pembelian"))
        self.pushButton_5.setText(_translate("MainWindow", "Penjualan"))
        self.pushButton_4.setText(_translate("MainWindow", "Data Pembeli"))
        self.pushButton_6.setText(_translate("MainWindow", "Keluar"))
        self.label.setText(_translate("MainWindow", "SISTEM MANAJEMEN APOTEK RIGA"))
        self.label_2.setText(_translate("MainWindow", "DASHBOARD"))
        self.label_3.setText(_translate("MainWindow", "Ringkasan Informasi Apotek Anda"))
        self.label_4.setText(_translate("MainWindow", "TOTAL OBAT"))
        self.label_16.setText(_translate("MainWindow", "128"))
        self.label_5.setText(_translate("MainWindow", "TOTAL SUPPLIER"))
        self.label_17.setText(_translate("MainWindow", "12"))
        self.label_6.setText(_translate("MainWindow", "PENJUALAN HARI INI"))
        self.label_18.setText(_translate("MainWindow", "2.350.000"))
        self.label_7.setText(_translate("MainWindow", "TRANSAKSI BULAN INI"))
        self.label_19.setText(_translate("MainWindow", "98"))
        self.label_20.setText(_translate("MainWindow", "Transaksi"))
        self.label_8.setText(_translate("MainWindow", "Transaksi Terbaru"))
        self.label_21.setText(_translate("MainWindow", "Tanggal"))
        self.label_22.setText(_translate("MainWindow", "Keterangan"))
        self.label_23.setText(_translate("MainWindow", " Hari Ini"))
        self.label_24.setText(_translate("MainWindow", "Penjualan #INV0028"))
        self.label_25.setText(_translate("MainWindow", "Kemarin"))
        self.label_26.setText(_translate("MainWindow", "Pembelian dari PT Abadi Farmasi"))
        self.label_9.setText(_translate("MainWindow", "Stok Menipis"))
        self.label_10.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_13.setText(_translate("MainWindow", "20 / 50 unit"))
        self.label_11.setText(_translate("MainWindow", "Amoxillin 500mg"))
        self.label_14.setText(_translate("MainWindow", "15 / 25 unit"))
        self.label_12.setText(_translate("MainWindow", "vitamin C"))
        self.label_15.setText(_translate("MainWindow", "5 / 20 unit"))
        self.label_27.setText(_translate("MainWindow", "Transaksi Terbaru"))
        self.label_28.setText(_translate("MainWindow", "Tanggal"))
        self.label_29.setText(_translate("MainWindow", "Keterangan"))
        self.label_34.setText(_translate("MainWindow", "Catbgane"))
        self.label_30.setText(_translate("MainWindow", " Hari Ini"))
        self.label_31.setText(_translate("MainWindow", "Penjualan #INV0028"))
        self.label_35.setText(_translate("MainWindow", "Remaa"))
        self.label_32.setText(_translate("MainWindow", "Kemarin"))
        self.label_33.setText(_translate("MainWindow", "Pembelian dari PT Abadi Farmasi"))
        self.label_36.setText(_translate("MainWindow", "Khamen"))
