# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'penjualan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 200))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#0000d4\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/medicine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/supplier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/grocery-store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/exploratory-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #ff3333;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: none;\n"
"\n"
"    /* Glow merah */\n"
"    box-shadow: 0 0 10px rgba(255, 50, 50, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e62828;\n"
"    box-shadow: 0 0 14px rgba(255, 50, 50, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c71f1f;\n"
"    box-shadow: none;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 500))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#ffffff\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:#dddddd}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(20, 16, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("/* Gaya Dasar untuk Tombol Aksi */\n"
"QPushButton {\n"
"    /* Menghilangkan background dan border default */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 5px; \n"
"    border-radius: 4px;\n"
"    icon-size: 18px; /* Sedikit lebih besar */\n"
"}\n"
"\n"
"/* Gaya saat kursor mouse berada di atas tombol (Hover Effect) */\n"
"QPushButton:hover {\n"
"    /* LATAR BELAKANG BIRU TUA saat di-hover */\n"
"    background-color: #0D47A1; \n"
"    \n"
"    /* Mengubah warna ikon menjadi putih agar terlihat kontras di latar belakang biru */\n"
"    color: white; \n"
"}\n"
"\n"
"/* Gaya saat tombol ditekan (Pressed Effect) */\n"
"QPushButton:pressed {\n"
"    background-color: #0A3C8B; /* Warna biru sedikit lebih gelap saat ditekan */\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(574, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1e5fbf;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Downloads/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(30, 70, 431, 261))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 411, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(120, 30, 101, 16))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setGeometry(QtCore.QRect(10, 70, 189, 49))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        self.label_13.setGeometry(QtCore.QRect(150, 30, 101, 16))
        self.label_13.setObjectName("label_13")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 189, 49))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(120, 30, 101, 16))
        self.label_16.setObjectName("label_16")
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setGeometry(QtCore.QRect(10, 130, 189, 49))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setGeometry(QtCore.QRect(120, 20, 101, 16))
        self.label_19.setObjectName("label_19")
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_11.setGeometry(QtCore.QRect(210, 10, 189, 49))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_11)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_11)
        self.label_22.setGeometry(QtCore.QRect(120, 30, 101, 16))
        self.label_22.setObjectName("label_22")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setGeometry(QtCore.QRect(210, 70, 189, 49))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_23 = QtWidgets.QLabel(self.frame_12)
        self.label_23.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_12)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_12)
        self.label_25.setGeometry(QtCore.QRect(120, 30, 101, 16))
        self.label_25.setObjectName("label_25")
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setGeometry(QtCore.QRect(210, 130, 189, 49))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_26 = QtWidgets.QLabel(self.frame_13)
        self.label_26.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_13)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_13)
        self.label_28.setGeometry(QtCore.QRect(120, 20, 101, 16))
        self.label_28.setObjectName("label_28")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(470, 70, 201, 261))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.frame_14 = QtWidgets.QFrame(self.frame_6)
        self.frame_14.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_30 = QtWidgets.QLabel(self.frame_14)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_30.setObjectName("label_30")
        self.comboBox = QtWidgets.QComboBox(self.frame_14)
        self.comboBox.setGeometry(QtCore.QRect(50, 10, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.frame_15 = QtWidgets.QFrame(self.frame_6)
        self.frame_15.setGeometry(QtCore.QRect(10, 80, 181, 51))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_31.setObjectName("label_31")
        self.label_36 = QtWidgets.QLabel(self.frame_15)
        self.label_36.setGeometry(QtCore.QRect(126, 10, 51, 20))
        self.label_36.setObjectName("label_36")
        self.label_32 = QtWidgets.QLabel(self.frame_6)
        self.label_32.setGeometry(QtCore.QRect(20, 140, 47, 13))
        self.label_32.setObjectName("label_32")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(20, 180, 171, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_33 = QtWidgets.QLabel(self.frame_6)
        self.label_33.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_6)
        self.label_34.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_34.setObjectName("label_34")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 230, 161, 31))
        self.pushButton_9.setStyleSheet("/* Gaya Dasar untuk Tombol Aksi */\n"
"QPushButton {\n"
"    /* Menghilangkan background dan border default */\n"
"    background-color: red;\n"
"    border: none;\n"
"    padding: 5px; \n"
"    border-radius: 4px;\n"
"    icon-size: 18px; /* Sedikit lebih besar */\n"
"}\n"
"\n"
"/* Gaya saat kursor mouse berada di atas tombol (Hover Effect) */\n"
"QPushButton:hover {\n"
"    /* LATAR BELAKANG BIRU TUA saat di-hover */\n"
"    background-color: #0D47A1; \n"
"    \n"
"    /* Mengubah warna ikon menjadi putih agar terlihat kontras di latar belakang biru */\n"
"    color: white; \n"
"}\n"
"\n"
"/* Gaya saat tombol ditekan (Pressed Effect) */\n"
"QPushButton:pressed {\n"
"    background-color: #0A3C8B; /* Warna biru sedikit lebih gelap saat ditekan */\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_37 = QtWidgets.QLabel(self.frame_6)
        self.label_37.setGeometry(QtCore.QRect(120, 140, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 191, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_16 = QtWidgets.QFrame(self.frame_4)
        self.frame_16.setGeometry(QtCore.QRect(30, 340, 621, 171))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_35 = QtWidgets.QLabel(self.frame_16)
        self.label_35.setGeometry(QtCore.QRect(20, 10, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_16)
        self.tableWidget.setGeometry(QtCore.QRect(20, 31, 611, 211))
        self.tableWidget.setRowCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_8.setText(_translate("MainWindow", "Stok Obat"))
        self.pushButton_2.setText(_translate("MainWindow", "Supplier"))
        self.pushButton_3.setText(_translate("MainWindow", "Pembelian"))
        self.pushButton_5.setText(_translate("MainWindow", "Penjualan"))
        self.pushButton_4.setText(_translate("MainWindow", "Data Pembeli"))
        self.pushButton_6.setText(_translate("MainWindow", "Keluar"))
        self.label.setText(_translate("MainWindow", "SISTEM MANAJEMEN APOTEK RIGA"))
        self.pushButton_7.setText(_translate("MainWindow", "Tambah"))
        self.label_4.setText(_translate("MainWindow", "Daftar Obat"))
        self.label_5.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_6.setText(_translate("MainWindow", "Stok : 120"))
        self.label_7.setText(_translate("MainWindow", "Rp 7.500"))
        self.label_11.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_12.setText(_translate("MainWindow", "Stok : 120"))
        self.label_13.setText(_translate("MainWindow", "7.500"))
        self.label_14.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_15.setText(_translate("MainWindow", "Stok : 120"))
        self.label_16.setText(_translate("MainWindow", "Rp 7.500"))
        self.label_17.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_18.setText(_translate("MainWindow", "Stok : 120"))
        self.label_19.setText(_translate("MainWindow", "Rp 7.500"))
        self.label_20.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_21.setText(_translate("MainWindow", "Stok : 120"))
        self.label_22.setText(_translate("MainWindow", "Rp 7.500"))
        self.label_23.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_24.setText(_translate("MainWindow", "Stok : 120"))
        self.label_25.setText(_translate("MainWindow", "Rp 7.500"))
        self.label_26.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_27.setText(_translate("MainWindow", "Stok : 120"))
        self.label_28.setText(_translate("MainWindow", "Rp 7.500"))
        self.label_29.setText(_translate("MainWindow", "Keranjang"))
        self.label_30.setText(_translate("MainWindow", "Nama :"))
        self.label_31.setText(_translate("MainWindow", "Paracetamol 500mg"))
        self.label_36.setText(_translate("MainWindow", "3x 7.500"))
        self.label_32.setText(_translate("MainWindow", "Total :"))
        self.lineEdit.setText(_translate("MainWindow", "Masukan uang bayar"))
        self.label_33.setText(_translate("MainWindow", "uang bayar"))
        self.label_34.setText(_translate("MainWindow", "Kembalian"))
        self.pushButton_9.setText(_translate("MainWindow", "Proses Pembayaran"))
        self.label_37.setText(_translate("MainWindow", "Rp 22.500"))
        self.label_2.setText(_translate("MainWindow", "Transaksi Penjualan"))
        self.label_3.setText(_translate("MainWindow", "Kelola transaksi penjualan obat"))
        self.label_35.setText(_translate("MainWindow", "Transaksi Terakhir"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tangal"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Member"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bayar"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Kembalian"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "2167"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "15/04/2025"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Siti Aminah"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Rp 75.000"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Rp 80.000"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "Rp 5.000"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "2267"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "14/04/2025"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "Budi Santoso"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "Rp 30.000"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "Rp 50.000"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "Rp 20.000"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "2367"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "12/04/2025"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "Aji Malik"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", " Rp 15.000"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "Rp 30.000"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("MainWindow", "Rp 15.000"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "2467"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "10/04/2025"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "Ratna Aisyah"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "Rp 10.000"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "Rp 20.000"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("MainWindow", "Rp 10.000"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
