# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stok.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 200))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#0000d4\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/medicine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/supplier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/grocery-store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/exploratory-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #ff3333;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: none;\n"
"\n"
"    /* Glow merah */\n"
"    box-shadow: 0 0 10px rgba(255, 50, 50, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e62828;\n"
"    box-shadow: 0 0 14px rgba(255, 50, 50, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c71f1f;\n"
"    box-shadow: none;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 500))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#ffffff\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:#dddddd}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(20, 16, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(524, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1e5fbf;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Downloads/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 651, 251))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #E0E0E0; /* Border abu-abu tipis */\n"
"    border-radius: 8px; /* Sudut membulat */\n"
"    outline: 0; /* Menghilangkan border focus saat diklik */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-bottom: 1px solid #E0E0E0; /* Hanya garis di bawah header */\n"
"    padding: 5px;\n"
"}")
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(410, 290, 121, 16))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(440, 150, 81, 16))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #E74C3C;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 20)
        self.progressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar_2.setGeometry(QtCore.QRect(440, 180, 81, 16))
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #F1C40F;\n"
"}\n"
"")
        self.progressBar_2.setProperty("value", 35)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar_3.setGeometry(QtCore.QRect(440, 210, 81, 16))
        self.progressBar_3.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #2ECC71;\n"
"}\n"
"")
        self.progressBar_3.setProperty("value", 75)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(300, 370, 55, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(420, 270, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(530, 270, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_8.setText(_translate("MainWindow", "Stok Obat"))
        self.pushButton_2.setText(_translate("MainWindow", "Supplier"))
        self.pushButton_3.setText(_translate("MainWindow", "Pembelian"))
        self.pushButton_5.setText(_translate("MainWindow", "Penjualan"))
        self.pushButton_4.setText(_translate("MainWindow", "Data Pembeli"))
        self.pushButton_6.setText(_translate("MainWindow", "Keluar"))
        self.label.setText(_translate("MainWindow", "SISTEM MANAJEMEN APOTEK RIGA"))
        self.pushButton_7.setText(_translate("MainWindow", "+ Tambah Obat"))
        self.label_2.setText(_translate("MainWindow", "Manajemen Obat"))
        self.label_3.setText(_translate("MainWindow", "Kelola data obat dan stok\n"
"\n"
"Tambah Obat\n"
""))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nama Obat"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kategori"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Satuan"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Paracetamol 500mg"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Obat Bebas"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Tablet"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "20 unit"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Amoxillin 500mg"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "Antibiotik"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "Kapsul"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "35 unit"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Vitamin C"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "Suplemen"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "Tablet"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "75 unit"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_9.setText(_translate("MainWindow", "Edit"))
        self.pushButton_10.setText(_translate("MainWindow", "Hapus"))
