# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 200))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#0000d4\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/medicine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/supplier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/grocery-store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"    /* Shadow halus */\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 40);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #c8c8c8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: none;  /* shadow hilang saat ditekan */\n"
"    border: 1px solid #bababa;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/exploratory-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #ff3333;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px 18px;\n"
"    border-radius: 14px;\n"
"    border: none;\n"
"\n"
"    /* Glow merah */\n"
"    box-shadow: 0 0 10px rgba(255, 50, 50, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e62828;\n"
"    box-shadow: 0 0 14px rgba(255, 50, 50, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c71f1f;\n"
"    box-shadow: none;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 500))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#ffffff\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:#dddddd}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(20, 16, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(574, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1e5fbf;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Downloads/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 191, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 70, 651, 341))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 631, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 631, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setGeometry(QtCore.QRect(550, 90, 31, 21))
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_9.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../write_17964667.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon7)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_10.setGeometry(QtCore.QRect(590, 90, 31, 21))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_10.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../remove_7855869.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon8)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setGeometry(QtCore.QRect(550, 130, 31, 21))
        self.pushButton_11.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_12.setGeometry(QtCore.QRect(550, 170, 31, 21))
        self.pushButton_12.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_13.setGeometry(QtCore.QRect(550, 200, 31, 21))
        self.pushButton_13.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon7)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_14.setGeometry(QtCore.QRect(590, 130, 31, 21))
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon8)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_15.setGeometry(QtCore.QRect(590, 170, 31, 21))
        self.pushButton_15.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon8)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_16.setGeometry(QtCore.QRect(590, 200, 31, 21))
        self.pushButton_16.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon8)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_8.setText(_translate("MainWindow", "Stok Obat"))
        self.pushButton_2.setText(_translate("MainWindow", "Supplier"))
        self.pushButton_3.setText(_translate("MainWindow", "Pembelian"))
        self.pushButton_5.setText(_translate("MainWindow", "Penjualan"))
        self.pushButton_4.setText(_translate("MainWindow", "Data Pembeli"))
        self.pushButton_6.setText(_translate("MainWindow", "Keluar"))
        self.label.setText(_translate("MainWindow", "SISTEM MANAJEMEN APOTEK RIGA"))
        self.pushButton_7.setText(_translate("MainWindow", "Tambah"))
        self.label_2.setText(_translate("MainWindow", "Supplier"))
        self.label_3.setText(_translate("MainWindow", "Kelola data supplier obat"))
        self.lineEdit.setText(_translate("MainWindow", "Cari Supplier"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nama Supplier"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Alamat"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Telepon"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Aksi"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "PT Sehat Farma"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "JL. Kesehatan No. 123"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "022-5556789"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "info@sehatfarma.co.id"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "CV Jaya Abadi"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "JL. Pahlawan No. 45"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "022-6678901"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "contact@jayabadi.com"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "UD Medka Prima"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "JL. Mawar No. 07"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "022-7789012"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "udmedika@gmail.com"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Apotek Segar Waras"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "JL. Anggrek No. 33"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "022-8890123"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "apoteksegar@gmail.com"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
